# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: runBash
    displayName: show Title
    type: boolean
    default: true
  - name: mavenBuild
    displayName: maven Build
    type: boolean
    default: false
  - name: installTerraform
    displayName: install Terraform
    type: boolean
    default: false
  - name: applyTerraform
    displayName: apply Terraform
    type: boolean
    default: false
  - name: destroyTerraform
    displayName: Destroy Terraform
    type: boolean
    default: false

variables:
  - template: variables/variables.yml
    parameters:
      env: prd

trigger:
- main

pool:
  mypool

stages:
  - jobs:
    - steps:
        - ${{ if parameters.runBash  }}:
            - task: Bash@3
              displayName: Run Pipeline in ${{ variables.region }} on ${{ variables.environment }}
              inputs:
                targetType: 'inline'
                script: |
                  echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
                  echo "I'm in " ${{ variables.region }}
                  echo "My build agent is" $HOSTNAME
                  echo "My Path is" $PWD 
                  echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<";

        - ${{ if parameters.mavenBuild }}:
            - task: Maven@3
              displayName: MavenBuild
              inputs:
                mavenPomFile: 'pom.xml'
                mavenOptions: '-Xmx3072m'
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.8'
                jdkArchitectureOption: 'x64'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                goals: 'package'

            - task: MavenAuthenticate@0
              inputs:
                artifactsFeeds: xinwenliu

        - ${{ if parameters.installTerraform }}:
            - task: TerraformInstaller@1
              displayName: install terraform
              inputs:
                terraformVersion: latest

  - ${{ parameters.applyTerraform }}:
      - template: iac/stage-iac-apply.yml
        parameters:
          initTerraform: true
          planTerraform: true
          applyTerraform: true

  - ${{ parameters.destroyTerraform }}:
      - template: iac/stage-iac-destroy.yml
        parameters:
          initTerraform: true
          planTerraform: true
          applyTerraform: true




