# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: RunBash
    displayName: Run Bash
    type: boolean
    default: true

variables:
  - template: variables/variables.yml
    parameters:
      env: prd

trigger:
- main

pool:
  mypool

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: xinwenliu
    
- task: Maven@3
  displayName: MavenBuild
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- ${{ if parameters.RunBash  }}: 
  - task: Bash@3
    displayName: RunBash in ${{ variables.region }} on ${{ variables.environment }}
    inputs:
      targetType: 'inline'
      script: |
        echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
        echo $PWD $HOSTNAME ${{ variables.region }}
        echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<";

- task: TerraformInstaller@1
  displayName: install terraform
  inputs:
    terraformVersion: latest