# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

parameters:
  - name: RunBash
    displayName: Run Bash
    type: boolean
    default: true
  - name: initTerraform
    displayName: init Terraform
    type: boolean
    default: false

variables:
  - template: variables/variables.yml
    parameters:
      env: prd

trigger:
- main

pool:
  mypool

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: xinwenliu
    
- task: Maven@3
  displayName: MavenBuild
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- ${{ if parameters.RunBash  }}: 
  - task: Bash@3
    displayName: RunBash in ${{ variables.region }} on ${{ variables.environment }}
    inputs:
      targetType: 'inline'
      script: |
        echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>";
        echo $PWD $HOSTNAME ${{ variables.region }}
        echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<";

- task: TerraformInstaller@1
  displayName: install terraform
  inputs:
    terraformVersion: latest

- ${{ if parameters.initTerraform }}:
  - task: TerraformCLI@0
    displayName: 'terraform init'
    inputs:
      command: init
      workingDirectory: template/iac
      # set to `aws` to use aws backend
      backendType: aws
      # service connection name, required if backendType = aws
      backendServiceAws: my-aws-connection
      # s3 bucket's region, optional if provided elsewhere (i.e. inside terraform template or command options)
      backendAwsRegion: us-east-2
      # s3 bucket name, optional if provided elsewhere (i.e. inside terraform template or command options)
      backendAwsBucket: mysuppertfbackend
      # s3 path to state file, optional if provided elsewhere (i.e. inside terraform template or command options)
      backendAwsKey: 'mysuppertfbackend/dev-infrax'