---
- name: APT Install
  include_tasks:
    file: aptinstall.yml
    apply:
      tags: aptinstall
  tags: aptinstall


- name: Copy VSTS
  include_tasks:
    file: copyvsts.yml
    apply:
      tags: copyvsts
  tags: copyvsts


- name: configure Build Agent
  include_tasks:
    file: installbuildagent.yml
    apply:
      tags: ba
  tags: ba

