---
- name : Provision an EC2 instance with a public IP address
  amazon.aws.ec2_instance:
    name: myAgent
    key_name: 1648783368
    vpc_subnet_id: subnet-01c75925be0cde0ab
    instance_type: t2.micro
    security_group: launch-wizard-1
    network:
      assign_public_ip: true
    image_id: ami-05fb0b8c1424f266b
  register: result

- name: Display Registered Output
  debug:
    var: result



